# Generated by Django 3.1.7 on 2021-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210310_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='makaleye resim'),
        ),
    ]
